cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'findutils'
brew 'git'
brew 'go'
brew 'grc'
brew 'hub'
brew 'jenv'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'mongodb'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'readline'
brew 'redis'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

cask '1password'
cask 'charles'
cask 'cleanmymac'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'hyper'
cask 'iterm2'
cask 'java'
cask 'java7'
cask 'keybase'
cask 'pritunl'
cask 'slack'
cask 'spotify'
cask 'transmit'
cask 'virtualbox'
cask 'vivaldi'
cask 'xquartz'