cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'findutils'
brew 'git'
brew 'go'
brew 'grc'
brew 'hub'
brew 'jenv'
brew 'jp2a'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'maven'
brew 'mongodb'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'readline'
brew 'redis'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'unrar'
brew 'wget'
brew 'yarn' --ignore-dependencies
brew 'youtube-dl'
brew 'zsh'

cask '1password'
cask 'charles'
cask 'discord'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'graphql-playground'
cask 'hyper'
cask 'insomnia'
cask 'java'
cask 'keybase'
cask 'muzzle'
cask 'pritunl'
cask 'robo-3t'
cask 'slack'
cask 'spotify'
cask 'transmit'
cask 'visual-studio-code'
cask 'vivaldi'
cask 'xquartz'
cask 'zoomus'