"use strict";

module.exports = {
  config: {
    updateChannel: "stable",
    fontSize: 18,
    fontFamily: "Fira Code, Consolas, Menlo, monospace",
    fontWeight: "normal",
    fontWeightBold: "bold",
    lineHeight: 1.1,
    letterSpacing: 0,
    cursorColor: "rgba(248, 28, 229, 0.8)",
    cursorAccentColor: "#000",
    cursorShape: "BLOCK",
    cursorBlink: true,
    foregroundColor: "#fff",
    backgroundColor: "#000",
    selectionColor: "rgba(248, 28. 229, 0.3)",
    borderColor: "#333",
    css: "",
    termCSS: "",
    workingDirectory: "",
    showHamburgerMenu: "",
    showWindowControls: "",
    padding: "12px 14px",
    colors: {
      black: "#000000",
      red: "#c41e14",
      green: "#1dc121",
      yellow: "#c7c329",
      blue: "#0a2fc4",
      magenta: "#c839c5",
      cyan: "#20c5c6",
      white: "#c7c7c7",
      lightBlack: "#686868",
      lightRed: "#fd6f6b",
      lightGreen: "#67f8f6",
      lightYellow: "#fffa72",
      lightBlue: "#6a78fb",
      lightMagenta: "#fd7cfc",
      lightCyan: "#68fdfe",
      lightWhite: "#ffffff",
      limeGreen: "#32cd32",
      lightCoral: "#f08080",
    },
    shell: "",
    shellArgs: ["--login"],
    env: {},
    bell: "SOUND",
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: "vertical",
    webGLRenderer: true,
    webLinksActivationKey: "",
    disableLigatures: false,
    disableAutoUpdates: false,
    screenReaderMode: false,
    preserveCWD: true,
    hyperBorder: {
      borderColors: ["#53fdbb", "#9a4ff9"],
      borderWidth: "10px",
      animate: true,
    },
  },
  plugins: ["hyperocean", "hyperborder", "hyper-highlight-active-pane"],
  localPlugins: [],
  keymaps: {},
};
