#!/bin/sh
#
# Computer, become self-aware.
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

echo "› Becoming self-aware..."

# Run Homebrew through the Brewfile
echo "› Install brew bundle..."
brew bundle install

# find the installers and run them iteratively
echo "› Running installer scripts..."
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done