#!/bin/sh
#
# Yarn
#
# Install Yarn from shell script

echo "==> Installing Yarn package manager"

rm -rf ~/.yarn
curl -o- -L https://yarnpkg.com/install.sh | bash

echo "==> Yarn install finished..."